openapi: 3.0.1
info:
  title: ablity202404
  version: 1.0.0
paths:
  /hello:
    get:
      summary: hello
      operationId: getHello
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string