openapi: 3.0.4
info:
  title: 能力目標202405
  description: Hellow
  version: 1.0.12

tags:
  - name: crud
    description: Operations about user
paths:
  /user/{username}:
    get:
      tags:
        - user
      summary: ユーザ参照API
      description: ユーザ名検索
      operationId: getUserByName
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: 接続エラー
        '404':
          description: 該当ユーザなし
        default:
          description: その他エラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      tags:
        - user
      summary: ユーザ名更新
      description: ユーザ名更新処理
      operationId: updateUser
      parameters:
        - name: username
          in: path
          description: name that need to be deleted
          required: true
          schema:
            type: string
      requestBody:
        description: ユーザ名更新結果
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: ユーザ名更新官僚
        '400':
          description: 接続エラー
        '404':
          description: 該当ユーザなし
        default:
          description: エラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - user
      summary: ユーザ削除
      description: ユーザ削除
      operationId: deleteUser
      parameters:
        - name: username
          in: path
          description: 削除対象ユーザ名
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ユーザ削除官僚
        '400':
          description: 接続エラー
        '404':
          description: 該当ユーザなし
        default:
          description: その他エラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
        phone:
          type: string
          example: '12345'
        userStatus:
          type: integer
          description: User Status
          format: int32
          example: 1
      xml:
        name: user
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  requestBodies:
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header